### ISSUE TITLE
TrojanDownloader.JS.bazv

### ISSUE THREAD

**Issue by ip-gamers** [Mohddanishb/danishmehraj.com#1]
Virustotal is fighting!

https://www.virustotal.com/gui/file-analysis/ODlkOTc4YzY4MDYyZTY3NTUzNDE2Mjc5OGVlYTBhNDc6MTY4MzQ1MzA5OQ==

**Comment by SwimmingTiger** [comment]
If every file is not malicious, why would a source code zip packaged by github be malicious?

We can only assume that part of the byte sequence of this packet happens to resemble part of a piece of malware.

But it's just a package of source code automatically generated by github, and it will never be run as an executable program.

That's why I advocate removing antivirus software with outdated technology from VirusTotal.

![image](https://user-images.githubusercontent.com/4986069/236674992-eb0f5e01-60c9-4b22-b06a-af090f6a1959.png)
